name: Generate codelab

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install claat with go
        run: |
          go install github.com/googlecodelabs/tools/claat@latest
          export GOPATH=$HOME/Go
          export GOROOT=/usr/local/opt/go/libexec
          export PATH=$PATH:$GOPATH/bin
          export PATH=$PATH:$GOROOT/bin
          claat

      - name: Generate codelab
        run: |
          claat export -o ./docs How\ to\ codelab.md